"use client";
import { useCallback, useEffect, useRef, useState, useTransition } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { RefreshCw, Search } from "lucide-react";
import { Button, Input } from "@/design/components";
import { Inline, Stack, Text } from "@/design/primitives";
import type { NfcCardStatus } from "@/types/nfc-card";
import styles from "./cards.module.css";
const filters: readonly { label: string; value?: NfcCardStatus }[] = [{ label: "All" }, { label: "Available", value: "AVAILABLE" }, { label: "Activated", value: "ACTIVATED" }, { label: "Disabled", value: "DISABLED" }, { label: "Lost", value: "LOST" }, { label: "Archived", value: "ARCHIVED" }];
export function CardsToolbar({ initialSearch, initialStatus }: { initialSearch: string; initialStatus?: NfcCardStatus }) { const pathname = usePathname(), router = useRouter(), params = useSearchParams(), [search, setSearch] = useState(initialSearch), [pending, startTransition] = useTransition(), initialized = useRef(false); const update = useCallback((changes: Record<string, string | undefined>) => { const query = new URLSearchParams(params.toString()); for (const [key, value] of Object.entries(changes)) value ? query.set(key, value) : query.delete(key); query.delete("page"); startTransition(() => router.replace(`${pathname}?${query}`)); }, [params, pathname, router]); useEffect(() => { if (!initialized.current) { initialized.current = true; return; } const timer = setTimeout(() => update({ search: search.trim() || undefined }), 350); return () => clearTimeout(timer); }, [search, update]); return <Stack className={styles.toolbar} gap="sm"><Inline align="end" gap="sm" wrap><div className={styles.search}><Input aria-label="Search NFC cards" disabled={pending} onChange={(event) => setSearch(event.currentTarget.value)} placeholder="Search activation token, customer or workspace..." prefix={<Search />} value={search} /></div><Button aria-label="Refresh inventory" iconOnly leftIcon={<RefreshCw />} onClick={() => router.refresh()} size="sm" variant="ghost" /></Inline><fieldset className={styles.filters}><legend>Status</legend><Inline gap="xs" wrap>{filters.map((filter) => <button aria-pressed={initialStatus === filter.value || (!initialStatus && !filter.value)} className={styles.filterChip} disabled={pending} key={filter.label} onClick={() => update({ status: filter.value })} type="button">{filter.label}</button>)}</Inline></fieldset><Text aria-live="polite" className={styles.visuallyHidden}>{pending ? "Updating inventory" : "Inventory updated"}</Text></Stack>; }
