import { CreditCard, Download, RadioTower, Upload } from "lucide-react";
import { AdminPageHeader, Badge, Button } from "@/design/components";
import { Box, Grid, Heading, Inline, Stack, Text } from "@/design/primitives";
import { first, type SearchRecord } from "@/features/admin/admin-query";
import { getNfcCardService } from "@/lib/composition-root";
import { nfcCardQuerySchema } from "@/validation/nfc-card";
import { CardManager, type CardInventoryRow, GenerateCardsButton } from "./CardManager";
import { CardsDataGrid } from "./CardsDataGrid";
import { CardsToolbar } from "./CardsToolbar";
import styles from "./cards.module.css";
export default async function CardsPage({ searchParams }: { searchParams: Promise<SearchRecord> }) { const params = await searchParams, query = nfcCardQuerySchema.parse({ search: first(params.search), status: first(params.status), page: first(params.page), pageSize: first(params.pageSize), sortDirection: first(params.sortDirection) }), service = getNfcCardService(); const { page: result, summary } = await service.inventory(query); const rows: readonly CardInventoryRow[] = result.items.map((card) => ({ id: card.id, activationToken: card.activationToken, activationUrl: service.activationUrl(card.activationToken), status: card.status, customer: card.customer, workspaceSlug: card.workspace?.primaryCard?.slug ?? null, createdAtLabel: card.createdAt.toLocaleString(), activatedAtLabel: card.activatedAt?.toLocaleString() ?? "Not activated" })); const preserved = new URLSearchParams(); for (const [key, value] of Object.entries(params)) { const item = first(value); if (item && key !== "page") preserved.set(key, item); } const kpis = [{ label: "Total Cards", value: summary.TOTAL }, { label: "Available", value: summary.AVAILABLE }, { label: "Activated", value: summary.ACTIVATED }, { label: "Pending", value: summary.RESERVED }, { label: "Disabled", value: summary.DISABLED }]; return <CardManager initialGenerate={first(params.action)==="generate"}><Stack className={styles.page} gap="md"><AdminPageHeader actions={<><GenerateCardsButton label="Generate Tokens"/><Button disabled leftIcon={<Upload/>} size="sm" title="Card import is not available yet" variant="secondary">Import Cards</Button><Button as="a" href="/api/admin/cards/export" leftIcon={<Download/>} size="sm" variant="secondary">Export Cards</Button></>} breadcrumbs={[{id:"overview",label:"Overview",href:"/admin"},{id:"cards",label:"NFC Cards",current:true}]} description="Manage permanent NFC activation tokens and assignments." eyebrow="Physical inventory" title="NFC Cards"/><Grid as="section" className={styles.kpis} columns={5} gap="none">{kpis.map((item) => <Inline className={styles.kpi} justify="between" key={item.label}><Inline gap="sm"><Box className={styles.kpiIcon}><CreditCard /></Box><Stack gap="xs"><Text tone="muted" variant="caption">{item.label}</Text><Text as="strong" variant="title">{item.value}</Text></Stack></Inline></Inline>)}</Grid><section className={styles.workspace}><CardsToolbar initialSearch={query.search ?? ""} initialStatus={query.status} /><Inline className={styles.directoryHeader} justify="between"><Heading level={2} variant="title">Card Inventory</Heading><Badge variant="neutral">{result.total} results</Badge></Inline><CardsDataGrid currentPage={result.page} pageSize={result.pageSize} queryString={preserved.toString()} rows={rows} totalItems={result.total} totalPages={result.totalPages} /></section></Stack></CardManager>; }
