import { z } from "zod";
import type { LegacyMigrationReportDTO, LegacyMigrationSourceDTO } from "@/dto/legacy-migration.dto";
import type { CreateMigratedCardCommand, LegacyMigrationReadRepository, UnitOfWork } from "@/repositories";
import { defaultAppearanceSettings } from "@/validation/appearance";
const sourceSchema=z.object({id:z.string().min(1),slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),name:z.string().trim().min(1),email:z.string().email().nullable(),website:z.string().url().nullable(),urlHash:z.string().min(1)});
const socialMapSchema=z.record(z.string(),z.string());
function socialLinks(source:LegacyMigrationSourceDTO,issues:string[]){const values=new Map<string,string>();for(const link of source.normalizedLinks){if(z.url().safeParse(link.url).success)values.set(link.platform.toLowerCase(),link.url);else issues.push(`Invalid normalized social URL for ${link.platform}`)}try{const parsed=socialMapSchema.parse(JSON.parse(source.socialLinksJson||"{}"));for(const [platform,url] of Object.entries(parsed)){if(z.url().safeParse(url).success&&!values.has(platform.toLowerCase()))values.set(platform.toLowerCase(),url);else if(!z.url().safeParse(url).success)issues.push(`Invalid JSON social URL for ${platform}`)}}catch{issues.push("Invalid socialLinks JSON")}return [...values].map(([platform,url],position)=>({platform,label:null,url,position}));}
function buttons(source:LegacyMigrationSourceDTO){return [{label:"Call",url:source.phone?`tel:${source.phone.replace(/\s/g,"")}`:null},{label:"Email",url:source.email?`mailto:${source.email}`:null},{label:"Website",url:source.website},{label:"Directions",url:source.address?`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(source.address)}`:null}].filter((item):item is {label:string;url:string}=>Boolean(item.url)).map((item,position)=>({...item,position}));}
function commandFor(source:LegacyMigrationSourceDTO,issues:string[]):CreateMigratedCardCommand{return {legacyId:source.id,legacyHash:source.urlHash,customer:{displayName:source.name,email:source.email,phone:source.phone,locale:"en",timezone:"UTC",createdAt:source.createTime,updatedAt:source.updateTime},card:{slug:source.slug,name:source.name,publishedAt:source.createTime,createdAt:source.createTime,updatedAt:source.updateTime},profile:{fullName:source.name,headline:source.title||null,company:source.company||null,bio:source.bio,email:source.email,phone:source.phone,website:source.website,address:source.address,countryCode:null},appearance:defaultAppearanceSettings,socialLinks:socialLinks(source,issues),buttons:buttons(source)};}
export class LegacyCardMigrationService {constructor(private readonly sources:LegacyMigrationReadRepository,private readonly unitOfWork:UnitOfWork){}async execute():Promise<LegacyMigrationReportDTO>{const sources=await this.sources.listActive();const report:{scanned:number;migrated:{legacyId:string;cardId:string;slug:string}[];skipped:{legacyId:string;slug:string;reason:string}[];validationFailures:{legacyId:string;slug:string;issues:string[]}[]}={scanned:sources.length,migrated:[],skipped:[],validationFailures:[]};for(const source of sources){const validated=sourceSchema.safeParse(source);if(!validated.success){report.validationFailures.push({legacyId:source.id,slug:source.slug,issues:validated.error.issues.map(issue=>`${issue.path.join(".")}: ${issue.message}`)});continue}const issues:string[]=[];const command=commandFor(source,issues);if(issues.length)report.validationFailures.push({legacyId:source.id,slug:source.slug,issues});const result=await this.unitOfWork.execute(async repositories=>{if(await repositories.migrations.findMigratedCardId(source.id))return null;return repositories.migrations.createAggregate(command)});if(result)report.migrated.push({legacyId:source.id,...result});else report.skipped.push({legacyId:source.id,slug:source.slug,reason:"Already migrated"})}return report}}
