import Link from "next/link";
import { listSubscriptions } from "@/lib/composition-root";
import type { SubscriptionStatusDTO } from "@/dto/subscription.dto";
import s from "@/features/admin/admin-records.module.css";
import { subscriptionAction } from "@/features/admin/subscription-actions";

const statuses=["PENDING_PAYMENT","ACTIVE","EXPIRED","SUSPENDED","CANCELED"] as const;
const parseDate=(value?:string,end=false)=>value?new Date(value+"T"+(end?"23:59:59.999":"00:00:00.000")+"Z"):undefined;
export default async function SubscriptionsPage({searchParams}:{searchParams:Promise<{status?:string;expiresFrom?:string;expiresTo?:string;workspaceId?:string}>}){
 const query=await searchParams;const status=statuses.includes(query.status as typeof statuses[number])?query.status as SubscriptionStatusDTO:undefined;
 const rows=await listSubscriptions.execute({status,expiresFrom:parseDate(query.expiresFrom),expiresTo:parseDate(query.expiresTo,true),workspaceId:query.workspaceId?.trim()||undefined});
 return <><header className={s.pageHeader}><div><p className={s.eyebrow}>Operations</p><h1>Subscriptions</h1><p>Approve, activate, renew, suspend, and cancel manually managed Workspace subscriptions.</p></div></header>
 <form className={s.filters} aria-label="Subscription filters"><label>Status<select name="status" defaultValue={status??""}><option value="">All statuses</option>{statuses.map(value=><option key={value} value={value}>{value.replaceAll("_"," ")}</option>)}</select></label><label>Expires from<input type="date" name="expiresFrom" defaultValue={query.expiresFrom}/></label><label>Expires to<input type="date" name="expiresTo" defaultValue={query.expiresTo}/></label><label>Workspace<input name="workspaceId" defaultValue={query.workspaceId} placeholder="Workspace ID"/></label><div className={s.actions}><button className={s.primary} type="submit">Apply filters</button><Link className={s.secondary} href="/admin/subscriptions">Reset</Link></div></form>
 <section className={s.panel} aria-label="Subscription results"><div className={s.sectionStack}>{rows.map(row=><article className={s.summaryCard} key={row.id}><strong>{row.customerName} · {row.status.replaceAll("_"," ")}</strong><span>Workspace {row.workspaceId}</span><span>{row.expiresAt?"Expires "+row.expiresAt.toLocaleDateString():"Not activated"}</span><form action={subscriptionAction} className={s.actions}><input type="hidden" name="id" value={row.id}/>{(["PENDING_PAYMENT","SUSPENDED"].includes(row.status)||["ACTIVE","EXPIRED"].includes(row.status))&&<select name="duration" aria-label="Subscription duration" defaultValue={row.billingInterval==="YEARLY"?"YEARLY":"MONTHLY"}><option value="MONTHLY">Monthly</option><option value="YEARLY">Yearly</option></select>}{["PENDING_PAYMENT","SUSPENDED"].includes(row.status)&&<button className={s.primary} name="action" value="ACTIVATE">Activate</button>}{["ACTIVE","EXPIRED"].includes(row.status)&&<button className={s.primary} name="action" value="RENEW">Renew</button>}{row.status==="ACTIVE"&&<button className={s.secondary} name="action" value="SUSPEND">Suspend</button>}{!["CANCELED","EXPIRED"].includes(row.status)&&<button className={s.danger} name="action" value="CANCEL">Cancel</button>}</form></article>)}</div>{rows.length===0&&<div className={s.empty}><strong>No subscriptions found</strong><p>Adjust the filters or approve a pending manual payment.</p></div>}</section></>
}
