import { describe,expect,it,vi } from "vitest";
import { ManageSubscription } from "@/use-cases/subscription-platform";
import { ManualSubscriptionLifecycleService } from "@/services/manual-subscription-lifecycle.service";

const plan={id:"plan",key:"legacy",name:"Legacy",description:null,currency:"USD",monthlyMinor:null,quarterlyMinor:null,yearlyMinor:null,active:true,popular:false,badge:null,limits:{},sortOrder:0,archivedAt:null,features:[],createdAt:new Date(0),updatedAt:new Date(0)};
const subscription=(overrides:Record<string,unknown>={})=>({id:"sub",workspaceId:"workspace",customerId:"customer",customerName:"Customer",customerEmail:"customer@example.com",plan,status:"PENDING_PAYMENT" as const,billingInterval:"MONTHLY" as const,startsAt:null,expiresAt:null,activatedAt:null,renewedAt:null,expiredAt:null,canceledAt:null,suspendedAt:null,currentPeriodStart:null,currentPeriodEnd:null,createdAt:new Date(0),updatedAt:new Date(0),...overrides});

describe("manual subscription lifecycle",()=>{
 it("activates a pending subscription for one calendar month and audits the actor",async()=>{const updateSubscription=vi.fn(async(_id,input)=>subscription({...input}));const audit=vi.fn();const platform={findAdminByEmail:vi.fn(async()=>({id:"admin",email:"admin@example.com",roles:["SUPER_ADMIN"]})),findSubscription:vi.fn(async()=>subscription()),updateSubscription,audit};const uow={execute:(work:(repositories:unknown)=>unknown)=>work({platform})};const now=new Date("2026-01-31T12:00:00.000Z");const result=await new ManageSubscription(uow as never,()=>now).execute("admin@example.com",{id:"sub",action:"ACTIVATE",duration:"MONTHLY"});expect(result.status).toBe("ACTIVE");expect(result.expiresAt?.toISOString()).toBe("2026-02-28T12:00:00.000Z");expect(updateSubscription).toHaveBeenCalledOnce();expect(audit).toHaveBeenCalledWith(expect.objectContaining({workspaceId:"workspace",action:"SUBSCRIPTION_ACTIVATE"}))});
 it("expires overdue subscriptions and sends each due reminder through the existing provider",async()=>{const now=new Date("2026-07-22T08:00:00.000Z");const expiring=subscription({status:"ACTIVE",expiresAt:new Date("2026-07-29T08:00:00.000Z"),customer:{displayName:"Customer",email:"customer@example.com"}});const expired=subscription({status:"EXPIRED",expiresAt:new Date("2026-07-22T07:00:00.000Z"),customer:{displayName:"Customer",email:"customer@example.com"}});const repo={expireOverdue:vi.fn(async()=>[expired]),listActiveExpiringBy:vi.fn(async()=>[expiring]),getOrCreateReminder:vi.fn(async input=>({id:input.idempotencyKey,status:"PENDING" as const,idempotencyKey:input.idempotencyKey,recipient:input.recipient})),claimReminder:vi.fn(async()=>true),markReminderSent:vi.fn(),markReminderFailed:vi.fn(),findById:vi.fn()};const email={name:"test",send:vi.fn(async()=>({providerMessageId:"message"}))};const logger={debug:vi.fn(),info:vi.fn(),warn:vi.fn(),error:vi.fn()};const result=await new ManualSubscriptionLifecycleService(repo as never,email,logger,{from:"OI <oi@example.com>"},()=>now).runDaily();expect(result).toEqual({expired:1,queued:2,sent:2,failed:0});expect(email.send).toHaveBeenCalledTimes(2);expect(repo.getOrCreateReminder).toHaveBeenCalledWith(expect.objectContaining({type:"EXPIRY_7_DAYS"}));expect(repo.getOrCreateReminder).toHaveBeenCalledWith(expect.objectContaining({type:"EXPIRED"}))});
});
