import {describe,expect,it,vi} from "vitest";import type {EditorCardDTO} from "@/dto";import {NotFoundError,ValidationError} from "@/lib/errors";import type {AdminReadRepository} from "@/repositories/admin-read.repository";import {AdminReadService} from "@/services/admin-read.service";
const NOW=new Date("2026-07-20T10:15:00.000Z"),CARD_ID="0915a8e0-60eb-4cfc-b6dc-adcb01dd249a";
function repository(){return {dashboard:vi.fn(),listOrders:vi.fn(),getOrder:vi.fn(),listCustomers:vi.fn(),getCustomer:vi.fn(),listCards:vi.fn(),getCard:vi.fn()} as unknown as AdminReadRepository;}
const editorCard:EditorCardDTO={id:CARD_ID,customerId:"3d594650-c44b-4f60-8c9a-c0f44f57615d",slug:"sherif-osman-49486b01",name:"Sherif Card",status:"DRAFT",visibility:"PRIVATE",publishedAt:null,accessVersion:1,profile:{fullName:"Sherif Osman",headline:null,company:null,bio:null,email:null,phone:null,website:null,address:null,countryCode:null},themeConfig:null,buttons:[],socialLinks:[],createdAt:NOW,updatedAt:NOW};
describe("Sprint 11 Admin read service",()=>{
 it("uses a UTC day boundary for dashboard counts",async()=>{const repo=repository();vi.mocked(repo.dashboard).mockResolvedValue({metrics:{pendingOrders:0,approvedOrders:0,completedOrders:0,totalCustomers:0,totalCards:0,activeCards:0,cardsCreatedToday:0,totalVisits:0,cardsPublished:0,activeCustomers:0},recentOrders:[],recentCustomers:[],generatedAt:NOW});await new AdminReadService(repo,()=>NOW).dashboard();expect(repo.dashboard).toHaveBeenCalledWith(new Date("2026-07-20T00:00:00.000Z"),NOW);});
 it("validates and normalizes paginated Order filters with an inclusive end date",async()=>{const repo=repository();vi.mocked(repo.listOrders).mockResolvedValue({items:[],total:0,page:2,pageSize:20,totalPages:1});await new AdminReadService(repo).listOrders({search:"  Ada  ",status:"PENDING",paymentStatus:"PAID",from:"2026-07-01",to:"2026-07-20",page:"2",pageSize:"20",sortBy:"customerName",sortDirection:"asc"});expect(repo.listOrders).toHaveBeenCalledWith({search:"Ada",status:"PENDING",paymentStatus:"PAID",from:new Date("2026-07-01T00:00:00.000Z"),to:new Date("2026-07-21T00:00:00.000Z"),page:2,pageSize:20,sortBy:"customerName",sortDirection:"asc"});});
 it("rejects invalid query values before the repository",async()=>{const repo=repository();expect(()=>new AdminReadService(repo).listOrders({status:"NOT_REAL"})).toThrow(ValidationError);expect(repo.listOrders).not.toHaveBeenCalled();});
 it("maps missing detail records to explicit NotFoundError",async()=>{const repo=repository();vi.mocked(repo.getCustomer).mockResolvedValue(null);await expect(new AdminReadService(repo).getCustomer("3d594650-c44b-4f60-8c9a-c0f44f57615d")).rejects.toBeInstanceOf(NotFoundError);});
 it("returns a renderer-safe preview from the Card read source",async()=>{const repo=repository();vi.mocked(repo.getCard).mockResolvedValue({card:{id:CARD_ID,name:"Sherif Card",slug:editorCard.slug,status:"DRAFT",visibility:"PRIVATE",owner:{id:editorCard.customerId,displayName:"Sherif"},createdAt:NOW,updatedAt:NOW,publishedAt:null},owner:{id:editorCard.customerId,displayName:"Sherif",email:null,phone:null,status:"ACTIVE"},profile:editorCard.profile,editorCard,order:null,accessCode:null});const result=await new AdminReadService(repo).getCard(CARD_ID);expect(result.preview).toMatchObject({id:CARD_ID,slug:editorCard.slug,status:"DRAFT",visibility:"PRIVATE"});expect(result.preview).not.toHaveProperty("customerId");expect(result.preview).not.toHaveProperty("accessVersion");});
});
