import { describe, expect, it, vi } from "vitest";
import type { AccessCodeDTO, CardDTO, CustomerDTO, OrderDTO } from "@/dto";
import { InvalidOrderTransitionError } from "@/lib/errors";
import type { TransactionRepositories, UnitOfWork } from "@/repositories";
import { ApproveOrder, CancelOrder, CompleteOrder, CreateCard, CreateCustomer, CreateOrder, GenerateInitialAccessCode } from "@/use-cases";

const ORDER_ID="53bd8d70-8f9b-48bc-a7de-bbca23bdf033", CUSTOMER_ID="3d594650-c44b-4f60-8c9a-c0f44f57615d", CARD_ID="86bfda9c-ef1f-41b5-aec9-198cc664b42f", NOW=new Date("2026-07-20T10:00:00.000Z");
const baseOrder:OrderDTO={id:ORDER_ID,orderNumber:"OI-20260720-A1B2C3D4",customerName:"Ada Lovelace",company:"Analytical",email:"ada@example.com",phone:"+201000000000",package:"DIGITAL_NFC",quantity:1,notes:null,status:"PENDING",paymentStatus:"PENDING",fulfillmentStatus:"NOT_STARTED",customerId:null,cardIds:[],createdAt:NOW,updatedAt:NOW};
const customer:CustomerDTO={id:CUSTOMER_ID,displayName:"Ada Lovelace",email:"ada@example.com",phone:"+201000000000",status:"ACTIVE",locale:"en",timezone:"UTC",createdAt:NOW,updatedAt:NOW};
const card:CardDTO={id:CARD_ID,customerId:CUSTOMER_ID,slug:"ada-a1b2c3d4",name:"Ada Lovelace Card",status:"DRAFT",visibility:"PRIVATE",publishedAt:null,accessVersion:1,profile:{fullName:"Ada Lovelace",headline:null,company:"Analytical",bio:null,email:"ada@example.com",phone:"+201000000000",website:null,address:null,countryCode:null},createdAt:NOW,updatedAt:NOW};
const accessCode:AccessCodeDTO={id:"32ca1ea0-f889-49ff-aa1a-ab72691492e9",cardId:CARD_ID,version:1,status:"ACTIVE",expiresAt:null,lastUsedAt:null,useCount:0,createdAt:NOW,revokedAt:null};

function orderRepositories(initial:OrderDTO=baseOrder){let current=initial;const orders={findById:vi.fn(async()=>current),list:vi.fn(async()=>[current]),findAccountCredentials:vi.fn(async()=>null),findPendingRegistrationByEmail:vi.fn(async()=>null),create:vi.fn(async command=>{current={...baseOrder,...command};return current}),update:vi.fn(async(_id,command)=>{current={...current,...command,customerId:command.customerId===undefined?current.customerId:command.customerId};return current}),transition:vi.fn(async command=>{if(current.status!==command.fromStatus||command.fromFulfillmentStatus&&current.fulfillmentStatus!==command.fromFulfillmentStatus)return null;current={...current,...command.update};return current})};return {orders,get:()=>current};}
function repositories(order:ReturnType<typeof orderRepositories>):TransactionRepositories{return {orders:order.orders,customers:{findById:vi.fn(async()=>customer),create:vi.fn(async()=>customer),update:vi.fn(),provisionAccount:vi.fn(async()=>({accountId:"acct-1",workspaceId:"ws-1"}))},cards:{findById:vi.fn(async()=>card as any),findEditorById:vi.fn(),findRenderSourceBySlug:vi.fn(),create:vi.fn(async()=>card),update:vi.fn(),incrementAccessVersion:vi.fn(),updateAppearance:vi.fn(),slugExists:vi.fn(async()=>false)},accessCodes:{findByHash:vi.fn(),findLatestByCard:vi.fn(),findMaximumVersion:vi.fn(async()=>null),create:vi.fn(async()=>accessCode),updateMany:vi.fn(),markUsed:vi.fn(),recordEvent:vi.fn()},editorSessions:{findByTokenHash:vi.fn(),create:vi.fn(),revokeByCard:vi.fn()},legacy:{} as TransactionRepositories["legacy"],migrations:{} as TransactionRepositories["migrations"]};}
function trackedUow(repositories:TransactionRepositories){const execute=vi.fn(<T>(work:(value:TransactionRepositories)=>Promise<T>)=>work(repositories));return {unitOfWork:{execute} as UnitOfWork,execute};}

 describe("Sprint 10 Order lifecycle",()=>{
  it("creates a real pending order without provisioning customer or card",async()=>{const state=orderRepositories();const repos=repositories(state);const {unitOfWork}=trackedUow(repos);const result=await new CreateOrder(unitOfWork,{generate:()=>"OI-20260720-A1B2C3D4"},{now:()=>NOW}).execute({customerName:" Ada Lovelace ",email:"ada@example.com",phone:"+201000000000",package:"DIGITAL_NFC",quantity:1});expect(result.status).toBe("PENDING");expect(result.fulfillmentStatus).toBe("NOT_STARTED");expect(repos.customers.create).not.toHaveBeenCalled();expect(repos.cards.create).not.toHaveBeenCalled();});
  it("approves atomically and reuses transaction-scoped provisioning rules",async()=>{const state=orderRepositories();const repos=repositories(state);const tracked=trackedUow(repos);const forbidden:UnitOfWork={execute:vi.fn(()=>{throw new Error("nested transaction")})};const result=await new ApproveOrder(tracked.unitOfWork,new CreateCustomer(forbidden),new CreateCard(forbidden),new GenerateInitialAccessCode(forbidden,{hash:vi.fn(async()=>new Uint8Array([1,2,3]))},{generate:()=>"0123456789ABCDEFGHJKMNPQRS",format:value=>`OI-${value}`})).execute({orderId:ORDER_ID});expect(tracked.execute).toHaveBeenCalledTimes(1);expect(forbidden.execute).not.toHaveBeenCalled();expect(repos.cards.create).toHaveBeenCalledWith(expect.objectContaining({orderId:ORDER_ID,initialProfile:{company:"Analytical",email:"ada@example.com",phone:"+201000000000"}}));expect(repos.accessCodes.create).toHaveBeenCalledWith(expect.objectContaining({codeHash:new Uint8Array([1,2,3])}));expect(result.issuedAccessCodes[0].code).toBe("OI-0123456789ABCDEFGHJKMNPQRS");expect(result.order.status).toBe("FULFILLED");expect(result.order.fulfillmentStatus).toBe("ACCESS_CODE_ISSUED");});
  it("rejects invalid approval before provisioning",async()=>{const state=orderRepositories({...baseOrder,status:"CANCELLED"});const repos=repositories(state);const {unitOfWork}=trackedUow(repos);const forbidden:UnitOfWork={execute:vi.fn()};await expect(new ApproveOrder(unitOfWork,new CreateCustomer(forbidden),new CreateCard(forbidden),new GenerateInitialAccessCode(forbidden,{hash:vi.fn()},{generate:()=>"x",format:value=>value})).execute({orderId:ORDER_ID})).rejects.toBeInstanceOf(InvalidOrderTransitionError);expect(repos.customers.create).not.toHaveBeenCalled();});
  it("cancels only a cancellable order",async()=>{const state=orderRepositories();const repos=repositories(state);await new CancelOrder(trackedUow(repos).unitOfWork).execute({orderId:ORDER_ID});expect(state.get().status).toBe("CANCELLED");await expect(new CancelOrder(trackedUow(repos).unitOfWork).execute({orderId:ORDER_ID})).rejects.toBeInstanceOf(InvalidOrderTransitionError);});
  it("advances printing, delivery, and completion one explicit step at a time",async()=>{const state=orderRepositories({...baseOrder,status:"FULFILLED",fulfillmentStatus:"ACCESS_CODE_ISSUED"});const repos=repositories(state);const useCase=new CompleteOrder(trackedUow(repos).unitOfWork);expect((await useCase.execute({orderId:ORDER_ID})).fulfillmentStatus).toBe("PRINTING");expect((await useCase.execute({orderId:ORDER_ID})).fulfillmentStatus).toBe("DELIVERED");const complete=await useCase.execute({orderId:ORDER_ID});expect(complete.fulfillmentStatus).toBe("COMPLETED");expect(complete.status).toBe("COMPLETED");await expect(useCase.execute({orderId:ORDER_ID})).rejects.toBeInstanceOf(InvalidOrderTransitionError);});
});
