"use server";
import type { AuthOptions } from "next-auth";
import { getServerSession } from "next-auth/next";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { authOptions } from "@/lib/auth";
import { authorizeAdminAction, platformSettingsService } from "@/lib/composition-root";
import { getEnvironment } from "@/lib/env";
import { ResendEmailProvider } from "@/notifications/resend-email.provider";
import type { PlatformSettings } from "@/types/platform-settings";
const text=(form:FormData,key:string)=>String(form.get(key)??"").trim();
const list=(form:FormData,key:string)=>text(form,key).split(",").map(value=>value.trim()).filter(Boolean);
const checked=(form:FormData,key:string)=>form.get(key)==="on";
function readSettings(form:FormData):PlatformSettings{return {version:1,general:{platformName:text(form,"platformName"),platformLogo:text(form,"platformLogo"),favicon:text(form,"favicon"),timezone:text(form,"timezone"),currency:text(form,"currency"),defaultLanguage:text(form,"defaultLanguage")},contact:{supportEmail:text(form,"supportEmail"),supportPhone:text(form,"supportPhone"),whatsapp:text(form,"whatsapp"),companyAddress:text(form,"companyAddress")},email:{senderName:text(form,"senderName"),senderEmail:text(form,"senderEmail"),replyToEmail:text(form,"replyToEmail"),provider:text(form,"emailProvider") as PlatformSettings["email"]["provider"],providerSettings:text(form,"emailProviderSettings")},payment:{instapayAccount:text(form,"instapayAccount"),vodafoneCashNumber:text(form,"vodafoneCashNumber"),bankAccountDetails:text(form,"bankAccountDetails"),instructions:text(form,"paymentInstructions"),qrImage:text(form,"paymentQrImage"),acceptedProofTypes:list(form,"acceptedProofTypes")},uploads:{maxSizeMb:Number(text(form,"maxUploadSize")),allowedFileTypes:list(form,"allowedFileTypes")},security:{registrationEnabled:checked(form,"registrationEnabled"),maintenanceMode:checked(form,"maintenanceMode"),emailVerificationRequired:checked(form,"emailVerificationRequired"),sessionTimeoutMinutes:Number(text(form,"sessionTimeout"))},seo:{metaTitle:text(form,"metaTitle"),metaDescription:text(form,"metaDescription"),ogImage:text(form,"ogImage"),robots:text(form,"robots")},social:{facebook:text(form,"facebook"),instagram:text(form,"instagram"),linkedin:text(form,"linkedin"),x:text(form,"x"),youtube:text(form,"youtube")}}}
async function authorize(){const session=await getServerSession(authOptions as AuthOptions);const email=session?.user?.email;if(!email)throw new Error("Administrator authentication is required");await authorizeAdminAction.execute(email,"PLAN_MANAGE")}
const destination=(kind:"saved"|"tested"|"error",message?:string)=>"/admin/settings?"+kind+"="+encodeURIComponent(message??"1");
export async function savePlatformSettingsAction(form:FormData){let target:string;try{await authorize();await platformSettingsService.save(readSettings(form));revalidatePath("/","layout");target=destination("saved")}catch(error){target=destination("error",error instanceof Error?error.message:"Unable to save platform settings")}redirect(target)}
export async function sendPlatformTestEmailAction(form:FormData){let target:string;try{await authorize();const settings=await platformSettingsService.save(readSettings(form));const environment=getEnvironment();const recipient=settings.contact.supportEmail||settings.email.replyToEmail||settings.email.senderEmail;if(!recipient)throw new Error("Add a support, reply-to, or sender email before testing");const from=settings.email.senderEmail?settings.email.senderName+" <"+settings.email.senderEmail+">":environment.RESEND_FROM_EMAIL;await new ResendEmailProvider(environment.RESEND_API_KEY).send({from,to:recipient,subject:settings.general.platformName+" test email",html:"<p>Email delivery is configured for "+settings.general.platformName+".</p>",text:"Email delivery is configured for "+settings.general.platformName+"."},{idempotencyKey:"platform-settings-test/"+crypto.randomUUID()});revalidatePath("/","layout");target=destination("tested",recipient)}catch(error){target=destination("error",error instanceof Error?error.message:"Unable to send test email")}redirect(target)}
