import Link from "next/link";
import { adminReadService } from "@/lib/composition-root";
import s from "@/features/admin/admin-records.module.css";
import { Breadcrumbs, EmptyState, Pagination, StatusBadge, TableScroll, label } from "@/features/admin/AdminReadUI";
import { first, pageHref, type SearchRecord } from "@/features/admin/admin-query";
import { AccessCodeActions } from "@/features/admin/AccessCodeActions";

export default async function AccessCodesPage({ searchParams }: { searchParams: Promise<SearchRecord> }) {
  const params = await searchParams;
  const query = { search: first(params.search), status: first(params.status), page: first(params.page), pageSize: first(params.pageSize) };
  const result = await adminReadService.listAccessCodes(query);
  return <><Breadcrumbs items={[{ label: "Overview", href: "/admin" }, { label: "Access Codes" }]} /><header className={s.pageHeader}><div><p className={s.eyebrow}>Security operations</p><h1>Access Codes</h1><p>Manage issuance state and usage metadata. Historical plaintext is never retained or displayed.</p></div></header><form className={s.filters}><label>Search<input name="search" defaultValue={query.search} placeholder="Card, slug, customer" /></label><label>Status<select name="status" defaultValue={query.status ?? ""}><option value="">All statuses</option>{["ACTIVE", "ROTATED", "REVOKED", "EXPIRED"].map(value => <option key={value}>{value}</option>)}</select></label><button type="submit">Apply</button></form><section className={s.tablePanel}><div className={s.tableToolbar}><strong>Access codes</strong><span>{result.total} result{result.total === 1 ? "" : "s"}</span></div>{result.items.length ? <TableScroll><table className={s.table}><thead><tr><th>Card</th><th>Customer</th><th>Issued</th><th>Status</th><th>Last used</th><th>Expires</th><th>Actions</th></tr></thead><tbody>{result.items.map(code => <tr key={code.id}><td data-label="Card"><Link href={`/admin/cards/${code.cardId}`}><strong>{code.cardName}</strong><br /><code>{code.slug}</code></Link></td><td data-label="Customer">{code.customerName}</td><td data-label="Issued">{code.createdAt.toLocaleDateString()} · v{code.version}</td><td data-label="Status"><StatusBadge tone={code.status === "ACTIVE" ? "success" : code.status === "EXPIRED" || code.status === "REVOKED" ? "danger" : "neutral"}>{label(code.status)}</StatusBadge></td><td data-label="Last used">{code.lastUsedAt?.toLocaleString() ?? "Never"}</td><td data-label="Expires">{code.expiresAt?.toLocaleString() ?? "Never"}</td><td data-label="Actions"><AccessCodeActions cardId={code.cardId} active={code.status === "ACTIVE"} /></td></tr>)}</tbody></table></TableScroll> : <EmptyState title="No access codes" description="Codes appear when an administrator issues a card." />}<Pagination page={result.page} totalPages={result.totalPages} href={page => pageHref("/admin/access-codes", params, page)} /></section></>
}
