"use client";

import { useActionState, useMemo, useState, useTransition } from "react";
import { Archive, Plus } from "lucide-react";
import type { PlanDTO } from "@/dto/subscription.dto";
import { AdminPage, AdminPageHeader, Badge, Button, ConfirmationDialog, EmptyState, Input, Textarea } from "@/design/components";
import { DataTable, type DataGridColumn } from "@/design/data-grid";
import { Checkbox, Form, FormActions, FormRow, FormSection } from "@/design/forms";
import { Inline, Stack, Text } from "@/design/primitives";
import { planOperationAction, savePlanAction, type PlanFormState } from "./subscription-actions";

const initialState: PlanFormState = { ok: false, message: "" };
const money = (minor: number | null, currency: string) => minor == null ? "—" : new Intl.NumberFormat(undefined, { style: "currency", currency }).format(minor / 100);

function PlanForm({ currency, onCancel, plan }: { currency: string; onCancel?: () => void; plan?: PlanDTO }) {
  const [state, action, pending] = useActionState(savePlanAction, initialState);
  const limits = plan?.limits ?? {};
  const [choices, setChoices] = useState({ active: plan?.active ?? true, popular: plan?.popular ?? false, customDomain: Boolean(limits.customDomain), analytics: Boolean(limits.analytics), prioritySupport: Boolean(limits.prioritySupport) });
  const choice = (key: keyof typeof choices, label: string) => <Checkbox checked={choices[key]} label={label} name={key} onCheckedChange={(value) => setChoices((current) => ({ ...current, [key]: value }))} value="on"/>;
  return <Form action={action} error={!state.ok ? state.message : undefined} success={state.ok ? state.message : undefined}>{plan ? <input name="id" type="hidden" value={plan.id}/> : null}<FormSection description="Public identity, pricing, and display order." title="Plan details"><FormRow layout="two-columns"><Input defaultValue={plan?.name} error={state.errors?.name} label="Name" name="name" required/><Input defaultValue={plan?.key} error={state.errors?.slug} label="Slug" name="slug" required/><Textarea defaultValue={plan?.description ?? ""} label="Description" name="description"/><Input defaultValue={plan?.monthlyMinor == null ? "" : plan.monthlyMinor / 100} label="Monthly price" min={0} name="monthlyPrice" type="number"/><Input defaultValue={plan?.yearlyMinor == null ? "" : plan.yearlyMinor / 100} label="Yearly price" min={0} name="yearlyPrice" type="number"/><Input defaultValue={plan?.currency ?? currency} label="Currency" name="currency" required/><Input defaultValue={plan?.badge ?? ""} label="Badge" name="badge"/><Input defaultValue={plan?.sortOrder ?? 0} error={state.errors?.sortOrder} label="Sort order" min={0} name="sortOrder" required type="number"/></FormRow></FormSection><FormSection description="One feature key per line and the limits enforced by this plan." title="Features and limits"><FormRow layout="two-columns"><Textarea defaultValue={plan?.features.filter((item) => item.enabled).map((item) => item.key).join("\n") ?? ""} label="Features" name="features"/><Input defaultValue={limits.maxCards ?? 1} label="Max cards" min={0} name="maxCards" type="number"/><Input defaultValue={limits.maxLinks ?? 0} label="Max links" min={0} name="maxLinks" type="number"/><Input defaultValue={limits.maxTeamMembers ?? 0} label="Max team members" min={0} name="maxTeamMembers" type="number"/></FormRow><FormRow layout="auto-grid">{choice("active", "Active")}{choice("popular", "Popular")}{choice("customDomain", "Custom domain")}{choice("analytics", "Analytics")}{choice("prioritySupport", "Priority support")}</FormRow></FormSection><FormActions>{onCancel ? <Button disabled={pending} onClick={onCancel} type="button" variant="ghost">Cancel</Button> : null}<Button loading={pending} loadingLabel="Saving plan" type="submit">{plan ? "Save changes" : "Create plan"}</Button></FormActions></Form>;
}

function Operation({ label, operation, plan, variant = "ghost" }: { label: string; operation: "DUPLICATE" | "ARCHIVE" | "ACTIVATE" | "DEACTIVATE"; plan: PlanDTO; variant?: "ghost" | "danger" | "secondary" }) {
  const [confirming, setConfirming] = useState(false), [pending, startTransition] = useTransition();
  const destructive = operation === "ARCHIVE";
  const run = () => startTransition(async () => { const data = new FormData(); data.set("id", plan.id); data.set("operation", operation); await planOperationAction(data); setConfirming(false); });
  return <>{destructive ? <Button onClick={() => setConfirming(true)} size="xs" variant={variant}>{label}</Button> : <Button loading={pending} loadingLabel={label} onClick={run} size="xs" variant={variant}>{label}</Button>}<ConfirmationDialog confirmLabel="Archive plan" description={`Archive ${plan.name}? It will no longer be available for new purchases.`} loading={pending} onCancel={() => setConfirming(false)} onConfirm={run} open={confirming} title="Archive this plan?"/></>;
}

export function PlansManager({ defaultCurrency, plans }: { defaultCurrency: string; plans: readonly PlanDTO[] }) {
  const [creating, setCreating] = useState(false), [editing, setEditing] = useState<string | null>(null);
  const columns = useMemo<readonly DataGridColumn<PlanDTO>[]>(() => [{ id: "name", header: "Name", mobileLabel: "Plan", cell: (plan) => <Stack gap="xs"><Text as="strong" variant="small">{plan.name}</Text><Text tone="muted" variant="caption">/{plan.key}</Text></Stack> }, { id: "monthly", header: "Monthly", mobileLabel: "Monthly price", cell: (plan) => money(plan.monthlyMinor, plan.currency) }, { id: "yearly", header: "Yearly", mobileLabel: "Yearly price", cell: (plan) => money(plan.yearlyMinor, plan.currency) }, { id: "status", header: "Status", mobileLabel: "Status", cell: (plan) => <Badge variant={plan.archivedAt ? "neutral" : plan.active ? "success" : "warning"}>{plan.archivedAt ? "Archived" : plan.active ? "Active" : "Inactive"}</Badge> }, { id: "popular", header: "Popular", mobileLabel: "Popular", cell: (plan) => plan.popular ? <Badge variant="primary">{plan.badge || "Popular"}</Badge> : "—" }, { id: "sort", header: "Order", mobileLabel: "Sort order", accessor: "sortOrder" }, { id: "actions", header: "Actions", mobileLabel: "Actions", cell: (plan) => <Inline gap="xs" wrap><Button onClick={() => setEditing(editing === plan.id ? null : plan.id)} size="xs" variant="secondary">Edit</Button><Operation label="Duplicate" operation="DUPLICATE" plan={plan}/>{!plan.archivedAt ? <><Operation label={plan.active ? "Deactivate" : "Activate"} operation={plan.active ? "DEACTIVATE" : "ACTIVATE"} plan={plan}/><Operation label="Archive" operation="ARCHIVE" plan={plan} variant="danger"/></> : null}</Inline> }], [editing]);
  const edited = plans.find((plan) => plan.id === editing);
  return <AdminPage><AdminPageHeader actions={<Button leftIcon={<Plus/>} onClick={() => setCreating((value) => !value)}>{creating ? "Close form" : "Create plan"}</Button>} breadcrumbs={[{ id: "overview", label: "Overview", href: "/admin" }, { id: "plans", label: "Plans", current: true }]} description="Create and maintain plans used by the digital card experience." eyebrow="Commerce" title="Plans"/>{creating ? <PlanForm currency={defaultCurrency} onCancel={() => setCreating(false)}/> : null}{plans.length ? <DataTable caption="Available plans" columns={columns} getRowId={(plan) => plan.id} getRowLabel={(plan) => plan.name} rows={plans}/> : <EmptyState actions={<Button leftIcon={<Plus/>} onClick={() => setCreating(true)}>Create first plan</Button>} description="Create a plan to make it available to the digital card experience." icon={<Archive/>} title="No plans yet"/>}{edited ? <PlanForm currency={defaultCurrency} key={edited.id} onCancel={() => setEditing(null)} plan={edited}/> : null}</AdminPage>;
}
