import type { Prisma, PrismaClient } from "@/generated/prisma/client";
import type { LegacyMigrationSourceDTO } from "@/dto/legacy-migration.dto";
import type { CreateMigratedCardCommand, LegacyMigrationReadRepository, LegacyMigrationWriteRepository } from "./contracts";
import { serializeAppearance } from "@/validation/appearance";

const sourceSelect = { id:true,name:true,title:true,company:true,address:true,phone:true,email:true,website:true,bio:true,avatar:true,backgroundImage:true,socialLinksJson:true,templateId:true,urlHash:true,slug:true,createTime:true,updateTime:true } satisfies Prisma.LegacyBusinessCardSelect;
type SourceRow=Prisma.LegacyBusinessCardGetPayload<{select:typeof sourceSelect}>;
function mapSource(row:SourceRow):LegacyMigrationSourceDTO{return {id:row.id,userId:row.id,userName:null,userEmail:null,name:row.name,title:row.title,company:row.company,address:row.address,phone:row.phone,email:row.email,website:row.website,bio:row.bio,avatar:row.avatar,backgroundImage:row.backgroundImage,socialLinksJson:row.socialLinksJson,templateId:row.templateId,urlHash:row.urlHash,slug:row.slug,createTime:row.createTime,updateTime:row.updateTime,normalizedLinks:[]};}
export class PrismaLegacyMigrationReadRepository implements LegacyMigrationReadRepository { constructor(private readonly db:PrismaClient){} async listActive():Promise<LegacyMigrationSourceDTO[]>{return (await this.db.legacyBusinessCard.findMany({where:{isActive:true},orderBy:{createTime:"asc"},select:sourceSelect})).map(mapSource)} }
export class PrismaLegacyMigrationTransactionRepository implements LegacyMigrationWriteRepository { constructor(private readonly db:Prisma.TransactionClient){} async findMigratedCardId(legacyId:string):Promise<string|null>{return (await this.db.legacyIdentifier.findUnique({where:{legacySystem_entityType_legacyId:{legacySystem:"prototype",entityType:"BUSINESS_CARD",legacyId}},select:{cardId:true}}))?.cardId??null} async createAggregate(command:CreateMigratedCardCommand):Promise<{cardId:string;slug:string}>{const workspace=await this.db.workspace.create({data:{},select:{id:true}});const customer=await this.db.customer.create({data:{...command.customer,workspaceId:workspace.id},select:{id:true}});const card=await this.db.card.create({data:{workspaceId:workspace.id,customerId:customer.id,slug:command.card.slug,name:command.card.name,status:"PUBLISHED",visibility:"PUBLIC",publishedAt:command.card.publishedAt,themeConfig:serializeAppearance(command.appearance) as any,createdAt:command.card.createdAt,updatedAt:command.card.updatedAt,profile:{create:{...command.profile,createdAt:command.card.createdAt,updatedAt:command.card.updatedAt}},socialLinks:{create:command.socialLinks.map(link=>({...link,isVisible:true,createdAt:command.card.createdAt,updatedAt:command.card.updatedAt}))},buttons:{create:command.buttons.map(button=>({...button,isVisible:true,createdAt:command.card.createdAt,updatedAt:command.card.updatedAt}))},legacyIdentifiers:{create:{legacySystem:"prototype",entityType:"BUSINESS_CARD",legacyId:command.legacyId,legacyHash:command.legacyHash,createdAt:command.card.createdAt}}},select:{id:true,slug:true}});await this.db.workspace.update({where:{id:workspace.id},data:{customerId:customer.id,primaryCardId:card.id}});return {cardId:card.id,slug:card.slug}} }
