import type { AppearanceSettings } from "@/types/appearance";

export interface AppearancePreset { id: "default"|"minimal"|"dark"|"luxury"|"coffee"|"ocean"|"sunset"; name: string; description: string; settings: AppearanceSettings }
const sections={profile:true,bio:true,contact:true,buttons:true,socialLinks:true};
export const appearancePresets:readonly AppearancePreset[]=[
 {id:"default",name:"Default",description:"Clean blue and slate",settings:{colors:{primary:"#1d4ed8",accent:"#60a5fa",text:"#0f172a",mutedText:"#64748b"},background:{style:"SOLID",color:"#f8fafc",gradientFrom:"#eff6ff",gradientTo:"#f8fafc"},typography:"SANS",buttonStyle:"SOLID",borderRadius:16,shadow:"MEDIUM",sections:{...sections}}},
 {id:"minimal",name:"Minimal",description:"Quiet monochrome clarity",settings:{colors:{primary:"#18181b",accent:"#a1a1aa",text:"#18181b",mutedText:"#71717a"},background:{style:"SOLID",color:"#ffffff",gradientFrom:"#ffffff",gradientTo:"#f4f4f5"},typography:"SYSTEM",buttonStyle:"OUTLINE",borderRadius:6,shadow:"NONE",sections:{...sections}}},
 {id:"dark",name:"Dark",description:"High-contrast night mode",settings:{colors:{primary:"#a78bfa",accent:"#22d3ee",text:"#f8fafc",mutedText:"#94a3b8"},background:{style:"GRADIENT",color:"#0f172a",gradientFrom:"#020617",gradientTo:"#1e293b"},typography:"SANS",buttonStyle:"SOFT",borderRadius:18,shadow:"LARGE",sections:{...sections}}},
 {id:"luxury",name:"Luxury",description:"Black, ivory, and gold",settings:{colors:{primary:"#a16207",accent:"#facc15",text:"#1c1917",mutedText:"#78716c"},background:{style:"GRADIENT",color:"#fafaf9",gradientFrom:"#fffbeb",gradientTo:"#e7e5e4"},typography:"SERIF",buttonStyle:"OUTLINE",borderRadius:4,shadow:"LARGE",sections:{...sections}}},
 {id:"coffee",name:"Coffee",description:"Warm roasted neutrals",settings:{colors:{primary:"#78350f",accent:"#d97706",text:"#422006",mutedText:"#92400e"},background:{style:"GRADIENT",color:"#fef3c7",gradientFrom:"#fffbeb",gradientTo:"#fde68a"},typography:"SERIF",buttonStyle:"SOFT",borderRadius:20,shadow:"MEDIUM",sections:{...sections}}},
 {id:"ocean",name:"Ocean",description:"Deep blue coastal calm",settings:{colors:{primary:"#0369a1",accent:"#2dd4bf",text:"#082f49",mutedText:"#0e7490"},background:{style:"GRADIENT",color:"#ecfeff",gradientFrom:"#e0f2fe",gradientTo:"#ccfbf1"},typography:"SANS",buttonStyle:"SOLID",borderRadius:22,shadow:"MEDIUM",sections:{...sections}}},
 {id:"sunset",name:"Sunset",description:"Warm coral evening",settings:{colors:{primary:"#c2410c",accent:"#e11d48",text:"#431407",mutedText:"#9a3412"},background:{style:"GRADIENT",color:"#fff7ed",gradientFrom:"#ffedd5",gradientTo:"#ffe4e6"},typography:"SANS",buttonStyle:"SOFT",borderRadius:24,shadow:"LARGE",sections:{...sections}}},
];
export function copyPreset(preset:AppearancePreset):AppearanceSettings{return {colors:{...preset.settings.colors},background:{...preset.settings.background},typography:preset.settings.typography,buttonStyle:preset.settings.buttonStyle,borderRadius:preset.settings.borderRadius,shadow:preset.settings.shadow,sections:{...preset.settings.sections}}}
