export const designTokens = {
  colors: {
    background: "--oi-color-background",
    surface: "--oi-color-surface",
    elevated: "--oi-color-surface-elevated",
    accent: "--oi-color-accent",
    text: "--oi-color-text",
    muted: "--oi-color-text-muted",
    primary: "--oi-color-primary", success: "--oi-color-success", warning: "--oi-color-warning", danger: "--oi-color-danger", info: "--oi-color-info", border: "--oi-color-border", overlay: "--oi-color-overlay", focus: "--oi-color-focus", hover: "--oi-color-hover", disabled: "--oi-color-disabled",
  },
  typography: {
    sans: "--oi-font-family-sans",
    display: "--oi-font-family-display",
    mono: "--oi-font-family-mono",
  },
  spacing: "--oi-space-",
  radius: "--oi-radius-",
  shadows: "--oi-shadow-",
  blur: "--oi-blur-",
  motion: { duration: "--oi-duration-", easing: "--oi-ease-", hero: "--oi-motion-hero-", spring: "--oi-motion-spring-", hover: "--oi-motion-hover-", press: "--oi-motion-press-", exit: "--oi-motion-exit-", page: "--oi-motion-page-", reveal: "--oi-motion-reveal-", card: "--oi-motion-card-", floating: "--oi-motion-floating-", glow: "--oi-motion-glow-", focus: "--oi-motion-focus-" },
  layout: { container: "--oi-container-", breakpoint: "--oi-breakpoint-", grid: "--oi-grid-", sidebar: "--oi-sidebar-", header: "--oi-header-", safeArea: "--oi-safe-area-" },
  zIndex: "--oi-z-",
  opacity: "--oi-opacity-",
  surfaces: {
    background: "--oi-surface-background",
    default: "--oi-surface-default",
    elevated: "--oi-surface-raised",
    floating: "--oi-surface-floating",
    overlay: "--oi-surface-modal",
    interactive: "--oi-surface-interactive",
  },
  glass: {
    xs: "--oi-glass-xs-",
    sm: "--oi-glass-sm-",
    md: "--oi-glass-md-",
    lg: "--oi-glass-lg-",
    xl: "--oi-glass-xl-",
  },
  elevation: "--oi-elevation-",
  borders: "--oi-border-",
  overlays: "--oi-overlay-",
} as const;
