ALTER TYPE "NfcCardStatus" RENAME VALUE 'ASSIGNED' TO 'ACTIVATION_PENDING';
ALTER TYPE "NfcCardStatus" ADD VALUE 'LOST';
CREATE TYPE "ActivationStatus" AS ENUM ('PENDING', 'ACTIVATED', 'EXPIRED', 'CANCELLED');
CREATE TYPE "ActivationEventType" AS ENUM ('LINK_CREATED', 'LINK_USED', 'CARD_ACTIVATED', 'CUSTOMER_CREATED', 'WORKSPACE_CREATED', 'ACTIVATION_FAILED', 'ACTIVATION_EXPIRED');
ALTER TABLE "NfcCard" ADD COLUMN "digitalCardId" UUID, ADD COLUMN "activatedAt" TIMESTAMP(3);
CREATE UNIQUE INDEX "NfcCard_digitalCardId_key" ON "NfcCard"("digitalCardId");
CREATE TABLE "CustomerAccount" ("id" UUID NOT NULL, "customerId" UUID NOT NULL, "email" TEXT NOT NULL, "passwordHash" BYTEA NOT NULL, "passwordSalt" BYTEA NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CustomerAccount_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "CustomerAccount_customerId_key" ON "CustomerAccount"("customerId");
CREATE UNIQUE INDEX "CustomerAccount_email_key" ON "CustomerAccount"("email");
CREATE TABLE "CustomerSession" ("id" UUID NOT NULL, "accountId" UUID NOT NULL, "tokenHash" BYTEA NOT NULL, "expiresAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "revokedAt" TIMESTAMP(3), CONSTRAINT "CustomerSession_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "CustomerSession_tokenHash_key" ON "CustomerSession"("tokenHash");
CREATE INDEX "CustomerSession_accountId_expiresAt_idx" ON "CustomerSession"("accountId", "expiresAt");
CREATE TABLE "Workspace" ("id" UUID NOT NULL, "customerId" UUID NOT NULL, "primaryCardId" UUID NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Workspace_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Workspace_customerId_key" ON "Workspace"("customerId");
CREATE UNIQUE INDEX "Workspace_primaryCardId_key" ON "Workspace"("primaryCardId");
CREATE TABLE "Activation" ("id" UUID NOT NULL, "tokenHash" BYTEA NOT NULL, "nfcCardId" UUID NOT NULL, "status" "ActivationStatus" NOT NULL DEFAULT 'PENDING', "expiresAt" TIMESTAMP(3), "activatedAt" TIMESTAMP(3), "activatedByUserId" UUID, "customerId" UUID, "createdByAdminId" UUID NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Activation_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Activation_tokenHash_key" ON "Activation"("tokenHash");
CREATE INDEX "Activation_status_createdAt_idx" ON "Activation"("status", "createdAt");
CREATE INDEX "Activation_nfcCardId_status_idx" ON "Activation"("nfcCardId", "status");
CREATE INDEX "Activation_customerId_activatedAt_idx" ON "Activation"("customerId", "activatedAt");
CREATE UNIQUE INDEX "Activation_one_pending_per_card" ON "Activation"("nfcCardId") WHERE "status" = 'PENDING';
CREATE TABLE "ActivationEvent" ("id" UUID NOT NULL, "activationId" UUID NOT NULL, "type" "ActivationEventType" NOT NULL, "detail" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "ActivationEvent_pkey" PRIMARY KEY ("id"));
CREATE INDEX "ActivationEvent_activationId_createdAt_idx" ON "ActivationEvent"("activationId", "createdAt");
CREATE INDEX "ActivationEvent_type_createdAt_idx" ON "ActivationEvent"("type", "createdAt");
ALTER TABLE "NfcCard" ADD CONSTRAINT "NfcCard_digitalCardId_fkey" FOREIGN KEY ("digitalCardId") REFERENCES "Card"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CustomerAccount" ADD CONSTRAINT "CustomerAccount_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CustomerSession" ADD CONSTRAINT "CustomerSession_accountId_fkey" FOREIGN KEY ("accountId") REFERENCES "CustomerAccount"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Workspace" ADD CONSTRAINT "Workspace_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Workspace" ADD CONSTRAINT "Workspace_primaryCardId_fkey" FOREIGN KEY ("primaryCardId") REFERENCES "Card"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Activation" ADD CONSTRAINT "Activation_nfcCardId_fkey" FOREIGN KEY ("nfcCardId") REFERENCES "NfcCard"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Activation" ADD CONSTRAINT "Activation_activatedByUserId_fkey" FOREIGN KEY ("activatedByUserId") REFERENCES "CustomerAccount"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Activation" ADD CONSTRAINT "Activation_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Activation" ADD CONSTRAINT "Activation_createdByAdminId_fkey" FOREIGN KEY ("createdByAdminId") REFERENCES "AdminUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "ActivationEvent" ADD CONSTRAINT "ActivationEvent_activationId_fkey" FOREIGN KEY ("activationId") REFERENCES "Activation"("id") ON DELETE CASCADE ON UPDATE CASCADE;
